# conda env create --file environment.yml
name: job_placement
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - pathlib
  - pandas
  - numpy
  - fs
  - seaborn
  - matplotlib
  - missingno
  - upsetplot
  - pip
  - scikit-learn
  - pyprojroot
  - python=3.9
  - joblib
  - pip:
    - pyhere
    